"""Shared installation constants."""
from .consts import (
    SAFE_APP_NAME, SAFE_NAME, REQUIRED_DEFAULTS, MARKER_NAME, UNIT_ROOT,
    ENVIRONMENT_FILE, ENVIRONMENT_KIND, INSTALLATION_KIND, JOURNAL_KIND,
    INSTALLATION_SUCCESS_STATUSES, LIFECYCLE_IDENTITY_VARIABLES,
    CONFIGURATION_PATH_FIELDS, CONFIGURATION_BOOLEAN_FIELDS,
    SOURCE_ENV_RELATIVE_PATH, GENERATED_CONFIGURATION_RELATIVE_PATH,
    GENERATED_ARTIFACT_RELATIVE_PATHS, DEV_RUNTIME_SOCKET_VARIABLES,
    INSTALLER_MODULE_NAME, INSTALLER_SOURCE_RELATIVE_PATH, INSTALLER_MODULE_RELATIVE_PATH,
    HELP_MANIFEST_FILES, LIFECYCLE_HOST_COMMANDS,
    APPLICATION_DIRECTORY_MODE, APPLICATION_FILE_MODE, APPLICATION_EXECUTABLE_MODE,
)
